- name: install
  hosts: all
  remote_user: ubuntu
  become: yes

  vars:
    app_file: ../deploy/app
    unit_file: ../app.service
    env_file: ../.env
  tasks:
    - name: make /var/www
      become: yes
      file:
        path: /var/www
        state: directory

    - name: make /var/log/app
      become: yes
      file:
        path: /var/log/app
        state: directory

    - name: add app file
      copy:
        src: "{{ app_file }}"
        dest: /var/www/app
        mode: 0655

    - name: add unit file
      copy:
        src: "{{ unit_file }}"
        dest: /etc/systemd/system/app.service

    - name: add env file
      copy:
        src: "{{ env_file }}"
        dest: /var/www/env

    - name: systemd
      systemd:
        name: app.service
        state: restarted
        daemon_reload: yes
        enabled: yes

